tr_code_to_path:dict = {
            
    # [업종] 시세
    "t1514" : "/indtp/market-data",
    "t8424" : "/indtp/market-data",
    "t1485" : "/indtp/market-data",
    "t1511" : "/indtp/market-data",
    "t1516" : "/indtp/market-data",

    # [업종] 차트
    "t4203" : "/indtp/chart",
    "t8417" : "/indtp/chart",
    "t8418" : "/indtp/chart",
    "t8419" : "/indtp/chart",

    # [업종] 실시간 시세
    "BM_" : "/websocket",

    # [주식] 시세
    "t1101" : "/stock/market-data",
    "t1102" : "/stock/market-data",
    "t1104" : "/stock/market-data",
    "t1105" : "/stock/market-data",
    "t1109" : "/stock/market-data",
    "t1301" : "/stock/market-data",
    "t1302" : "/stock/market-data",
    "t1305" : "/stock/market-data",
    "t1308" : "/stock/market-data",
    "t1310" : "/stock/market-data",
    "t1404" : "/stock/market-data",
    "t1405" : "/stock/market-data",
    "t1410" : "/stock/market-data",
    "t1422" : "/stock/market-data",
    "t1427" : "/stock/market-data",
    "t1442" : "/stock/market-data",
    "t1449" : "/stock/market-data",
    "t1471" : "/stock/market-data",
    "t1475" : "/stock/market-data",
    "t1486" : "/stock/market-data",
    "t1488" : "/stock/market-data",
    "t8407" : "/stock/market-data",
    "t9945" : "/stock/market-data",

    # [주식] 거래원
    "t1752" : "/stock/exchange",
    "t1764" : "/stock/exchange",
    "t1771" : "/stock/exchange",

    # [주식] 투자정보
    "t3102" : "/stock/investinfo",
    "t3202" : "/stock/investinfo",
    "t3320" : "/stock/investinfo",
    "t3341" : "/stock/investinfo",
    "t3401" : "/stock/investinfo",
    "t3518" : "/stock/investinfo",
    "t3521" : "/stock/investinfo",
    "t8428" : "/stock/investinfo",

    # [주식] 프로그램
    "t1631" : "/stock/program",
    "t1632" : "/stock/program",
    "t1633" : "/stock/program",
    "t1636" : "/stock/program",
    "t1637" : "/stock/program",
    "t1640" : "/stock/program",
    "t1662" : "/stock/program",

    # [주식] 투자자
    "t1601" : "/stock/investor",
    "t1602" : "/stock/investor",
    "t1603" : "/stock/investor",
    "t1615" : "/stock/investor",
    "t1617" : "/stock/investor",
    "t1621" : "/stock/investor",
    "t1664" : "/stock/investor",

    # [주식] 외인/기관
    "t1702" : "/stock/frgr-itt",
    "t1716" : "/stock/frgr-itt",
    "t1717" : "/stock/frgr-itt",

    # [주식] ELW
    "t1950" : "/stock/elw",
    "t1951" : "/stock/elw",
    "t1954" : "/stock/elw",
    "t1956" : "/stock/elw",
    "t1958" : "/stock/elw",
    "t1959" : "/stock/elw",
    "t1960" : "/stock/elw",
    "t1961" : "/stock/elw",
    "t1964" : "/stock/elw",
    "t1966" : "/stock/elw",
    "t1969" : "/stock/elw",
    "t1971" : "/stock/elw",
    "t1972" : "/stock/elw",
    "t1973" : "/stock/elw",
    "t1974" : "/stock/elw",
    "t1988" : "/stock/elw",
    "t8431" : "/stock/elw",
    "t9905" : "/stock/elw",
    "t9907" : "/stock/elw",
    "t9942" : "/stock/elw",

    # [주식] ETF
    "t1901" : "/stock/etf",
    "t1902" : "/stock/etf",
    "t1903" : "/stock/etf",
    "t1904" : "/stock/etf",
    "t1906" : "/stock/etf",

    # [주식] 섹터
    "t1531" : "/stock/sector",
    "t1532" : "/stock/sector",
    "t1533" : "/stock/sector",
    "t1537" : "/stock/sector",
    "t8425" : "/stock/sector",

    # [주식] 종목검색
    "t1809" : "/stock/item-search",
    "t1825" : "/stock/item-search",
    "t1826" : "/stock/item-search",
    "t1866" : "/stock/item-search",
    "t1859" : "/stock/item-search",
    "t1860" : "/stock/item-search",

    # [주식] 상위종목
    "t1441" : "/stock/high-item",
    "t1444" : "/stock/high-item",
    "t1452" : "/stock/high-item",
    "t1463" : "/stock/high-item",
    "t1466" : "/stock/high-item",
    "t1481" : "/stock/high-item",
    "t1482" : "/stock/high-item",
    "t1489" : "/stock/high-item",
    "t1492" : "/stock/high-item",

    # [주식] 차트
    "t1665" : "/stock/chart",
    "t8410" : "/stock/chart",
    "t8411" : "/stock/chart",
    "t8412" : "/stock/chart",

    # [주식] 기타
    "CLNAQ00100" : "/stock/etc",
    "t1403" : "/stock/etc",
    "t1411" : "/stock/etc",
    "t1638" : "/stock/etc",
    "t1921" : "/stock/etc",
    "t1926" : "/stock/etc",
    "t1927" : "/stock/etc",
    "t1941" : "/stock/etc",
    "t8430" : "/stock/etc",
    "t8436" : "/stock/etc",

    # [주식] 계좌
    "CDPCQ04700" : "/stock/accno",
    "CSPAQ00600" : "/stock/accno",
    "CSPAQ12200" : "/stock/accno",
    "CSPAQ12300" : "/stock/accno",
    "CSPAQ13700" : "/stock/accno",
    "CSPAQ22200" : "/stock/accno",
    "CSPBQ00200" : "/stock/accno",
    "FOCCQ33600" : "/stock/accno",
    "t0150" : "/stock/accno",
    "t0151" : "/stock/accno",
    "t0424" : "/stock/accno",
    "t0425" : "/stock/accno",

    # [주식] 주문
    "CSPAT00601" : "/stock/order",
    "CSPAT00701" : "/stock/order",
    "CSPAT00801" : "/stock/order",

    # [주식] 실시간 시세
    "B7_" : "/websocket",
    "DH1" : "/websocket",
    "DHA" : "/websocket",
    "DK3" : "/websocket",
    "DS3" : "/websocket",
    "DVI" : "/websocket",
    "H1_" : "/websocket",
    "H2_" : "/websocket",
    "HA_" : "/websocket",
    "HB_" : "/websocket",
    "I5_" : "/websocket",
    "IJ_" : "/websocket",
    "K1_" : "/websocket",
    "K3_" : "/websocket",
    "KH_" : "/websocket",
    "KM_" : "/websocket",
    "KS_" : "/websocket",
    "OK_" : "/websocket",
    "PH_" : "/websocket",
    "PM_" : "/websocket",
    "S2_" : "/websocket",
    "S3_" : "/websocket",
    "S4_" : "/websocket",
    "SC0" : "/websocket",
    "SC1" : "/websocket",
    "SC2" : "/websocket",
    "SC3" : "/websocket",
    "SC4" : "/websocket",
    "SHC" : "/websocket",
    "SHD" : "/websocket",
    "SHI" : "/websocket",
    "SHO" : "/websocket",
    "VI_" : "/websocket",
    "YJ_" : "/websocket",
    "YK3" : "/websocket",
    "YS3" : "/websocket",
    "ESN" : "/websocket",
    "h2_" : "/websocket",
    "h3_" : "/websocket",
    "k1_" : "/websocket",
    "s2_" : "/websocket",
    "s3_" : "/websocket",
    "s4_" : "/websocket",
    "Ys3" : "/websocket",
    "AFR" : "/websocket",

    # [선물/옵션] 시세
    "t2101" : "/futureoption/market-data",
    "t2105" : "/futureoption/market-data",
    "t2106" : "/futureoption/market-data",
    "t2201" : "/futureoption/market-data",
    "t2203" : "/futureoption/market-data",
    "t2210" : "/futureoption/market-data",
    "t2301" : "/futureoption/market-data",
    "t2405" : "/futureoption/market-data",
    "t2421" : "/futureoption/market-data",
    "t2830" : "/futureoption/market-data",
    "t2831" : "/futureoption/market-data",
    "t2832" : "/futureoption/market-data",
    "t2833" : "/futureoption/market-data",
    "t2835" : "/futureoption/market-data",
    "t8401" : "/futureoption/market-data",
    "t8402" : "/futureoption/market-data",
    "t8403" : "/futureoption/market-data",
    "t8404" : "/futureoption/market-data",
    "t8405" : "/futureoption/market-data",
    "t8406" : "/futureoption/market-data",
    "t8426" : "/futureoption/market-data",
    "t8427" : "/futureoption/market-data",
    "t8432" : "/futureoption/market-data",
    "t8433" : "/futureoption/market-data",
    "t8434" : "/futureoption/market-data",
    "t8435" : "/futureoption/market-data",
    "t8437" : "/futureoption/market-data",
    "t9943" : "/futureoption/market-data",
    "t9944" : "/futureoption/market-data",

    # [선물/옵션] 투자자
    "t2541" : "/futureoption/investor",
    "t2545" : "/futureoption/investor",

    # [선물/옵션] 차트
    "t2209" : "/futureoption/chart",
    "t8414" : "/futureoption/chart",
    "t8415" : "/futureoption/chart",
    "t8416" : "/futureoption/chart",
    "t8429" : "/futureoption/chart",

    # [선물/옵션] 계좌
    "CFOAQ00600" : "/futureoption/accno",
    "CFOAQ50600" : "/futureoption/accno",
    "CFOAQ10100" : "/futureoption/accno",
    "CFOBQ10500" : "/futureoption/accno",
    "CFOEQ11100" : "/futureoption/accno",
    "CFOEQ82600" : "/futureoption/accno",
    "CFOFQ02400" : "/futureoption/accno",
    "t0434" : "/futureoption/accno",
    "t0441" : "/futureoption/accno",
    "CEXAQ21100" : "/futureoption/accno",
    "CEXAQ21200" : "/futureoption/accno",
    "CEXAQ31100" : "/futureoption/accno",
    "CEXAQ31200" : "/futureoption/accno",
    "CEXAQ44200" : "/futureoption/accno",
    "FOCCQ33700" : "/futureoption/accno",

    # [선물/옵션] 주문
    "CFOAT00100" : "/futureoption/order",
    "CFOAT00200" : "/futureoption/order",
    "CFOAT00300" : "/futureoption/order",
    "CFOBQ10800" : "/futureoption/order",
    "CEXAT11100" : "/futureoption/order",
    "CEXAT11200" : "/futureoption/order",
    "CEXAT11300" : "/futureoption/order",

    # [선물/옵션] 기타
    "MMDAQ91200" : "/futureoption/etc",

    # [선물/옵션] 실시간 시세
    "C01" : "/websocket",
    "CD0" : "/websocket",
    "EC0" : "/websocket",
    "EH0" : "/websocket",
    "EU0" : "/websocket",
    "EU1" : "/websocket",
    "EU2" : "/websocket",
    "FC0" : "/websocket",
    "FD0" : "/websocket",
    "FH0" : "/websocket",
    "FX0" : "/websocket",
    "H01" : "/websocket",
    "JC0" : "/websocket",
    "JD0" : "/websocket",
    "JH0" : "/websocket",
    "JX0" : "/websocket",
    "O01" : "/websocket",
    "OC0" : "/websocket",
    "OD0" : "/websocket",
    "OH0" : "/websocket",
    "OMG" : "/websocket",
    "OX0" : "/websocket",
    "YC3" : "/websocket",
    "YFC" : "/websocket",
    "YJC" : "/websocket",
    "YOC" : "/websocket",

    # [해외선물] 시세
    "o3101" : "/overseas-futureoption/market-data",
    "o3104" : "/overseas-futureoption/market-data",
    "o3105" : "/overseas-futureoption/market-data",
    "o3106" : "/overseas-futureoption/market-data",
    "o3107" : "/overseas-futureoption/market-data",
    "o3116" : "/overseas-futureoption/market-data",
    "o3121" : "/overseas-futureoption/market-data",
    "o3123" : "/overseas-futureoption/market-data",
    "o3125" : "/overseas-futureoption/market-data",
    "o3126" : "/overseas-futureoption/market-data",
    "o3127" : "/overseas-futureoption/market-data",
    "o3128" : "/overseas-futureoption/market-data",
    "o3136" : "/overseas-futureoption/market-data",
    "o3137" : "/overseas-futureoption/market-data",

    # [해외선물] 계좌
    "CIDBQ01400" : "/overseas-futureoption/accno",
    "CIDBQ01500" : "/overseas-futureoption/accno",
    "CIDBQ01800" : "/overseas-futureoption/accno",
    "CIDBQ02400" : "/overseas-futureoption/accno",
    "CIDBQ03000" : "/overseas-futureoption/accno",
    "CIDBQ05300" : "/overseas-futureoption/accno",
    "CIDEQ00800" : "/overseas-futureoption/accno",

    # [해외선물] 주문
    "CIDBT00100" : "/overseas-futureoption/order",
    "CIDBT00900" : "/overseas-futureoption/order",
    "CIDBT01000" : "/overseas-futureoption/order",

    # [해외선물] 차트
    "o3103" : "/overseas-futureoption/chart",
    "o3108" : "/overseas-futureoption/chart",
    "o3117" : "/overseas-futureoption/chart",
    "o3139" : "/overseas-futureoption/chart",

    # [해외선물] 실시간 시세
    "OVC" : "/websocket",
    "OVH" : "/websocket",
    "WOC" : "/websocket",
    "WOH" : "/websocket",
    "TC1" : "/websocket",
    "TC2" : "/websocket",
    "TC3" : "/websocket",

    # [기타] 시간조회
    "t0167" : "/etc/time-search",

    # [기타] 실시간 시세
    "JIF" : "/websocket",
    "NWS" : "/websocket",

    # [실시간 시세 투자정보] 투자정보
    "BMT" : "/websocket",
    "CUR" : "/websocket",
    "MK2" : "/websocket",
}
